[updates]
auto_update = true

[style.description]
foreground = "purple"

[style.command_name]
foreground = "blue"

[style.example_code]
foreground = "green"

[style.example_variable]
foreground = "red"
