#!/usr/bin/env bash

BOOTSTRAP_DIR="$HOME/.config/yadm/bootstrap.d"

log_bootstrap() {
	local SCRIPT=$1
	bash "$BOOTSTRAP_DIR/$SCRIPT.sh" 2>&1 | tee "$BOOTSTRAP_LOG_DIR/$SCRIPT.log"
}

echo "Creating bootstrap logs directory..."
BOOTSTRAP_LOG_DIR="$HOME/yadm-bootstrap-logs"
mkdir -p "$BOOTSTRAP_LOG_DIR"

echo "Changing configurations to the one in Helen Chong's yadm repo..."
yadm restore .

log_bootstrap "locale"

echo "Installing software for these configuration files..."

log_bootstrap "pacman"
log_bootstrap "yay"
bash "$BOOTSTRAP_DIR/aur.sh"
log_bootstrap "extra-software"

echo "Downloading and installing the latest version of Karousel, the script to add scrollable tiling window management to KDE Plasma..."
mkdir -p "$HOME/Downloads" && cd "$HOME/Downloads" || return
curl -s https://api.github.com/repos/peterfajdiga/karousel/releases/latest |
	grep '"tarball_url":' |
	sed -E 's/.*"([^"]+)".*/\1/' |
	xargs curl -L |
	tar -xz -C ~/.local/share/kwin/scripts/
cd "$HOME" || return

log_bootstrap "catppuccin-kde"
log_bootstrap "klassy"

echo "Updating bat's binary cache to apply the Catppuccin Mocha theme..."
bat cache --build

log_bootstrap "mpv"
log_bootstrap "neovim"

echo "Updating Helen Chong's yadm repo origin URL..."
yadm remote set-url origin "git@git.helenchong.dev:helenchong/dotfiles.git"
echo "Updating Helen Chong's LazyVim configuration repo origin URL..."
cd "$HOME/.config/nvim" || return
git remote set-url origin "git@git.helenchong.dev:helenchong/LazyVim.git"
cd "$HOME" || return

echo "Changing the login shell to fish..."
chsh -s /usr/bin/fish

echo "yadm bootstrap program executed. Check out $BOOTSTRAP_LOG_DIR for logs."
echo "To complete the setup, select Fcitx 5 as the virtual keyboard in the system settings."
echo "Finally, reboot your system to apply changes."
