#!/usr/bin/env bash

echo "Changing Bash configuration to the one in Helen Chong's yadm repo..."
yadm restore .bashrc

echo "Setting up the system locale..."
locale_gen_file=/etc/locale.gen
# Reference: https://gist.github.com/le0me55i/e1f2244cdc0d64d8e541378357543b15
sudo sed -e '/en_GB.UTF-8/s/^#*//g' -i $locale_gen_file
sudo sed -e '/en_SG.UTF-8/s/^#*//g' -i $locale_gen_file
sudo sed -e '/ms_MY.UTF-8/s/^#*//g' -i $locale_gen_file
sudo locale-gen

echo "Cloning the Catppuccin global theme for KDE Plasma into the Downloads folder..."
mkdir -p Downloads && cd Downloads || return
git clone --depth=1 https://github.com/catppuccin/kde catppuccin-kde && cd catppuccin-kde || return
echo "Installing the Catppuccin global theme for KDE Plasma..."
chmod +x install.sh
./install.sh
cd "$HOME" || return

distro_id=$(lsb_release -i | cut -f 2-)
install_msg="Installing essential packages for these dot files..."

if [[ $distro_id == "Arch" ]]; then
    echo "$install_msg"
    sudo pacman -S fish zoxide starship neovim
fi

echo "Backing up Neovim files..."
mv ~/.config/nvim{,.bak}
mv ~/.local/share/nvim{,.bak}
mv ~/.local/state/nvim{,.bak}
mv ~/.cache/nvim{,.bak}
echo "Cloning Helen Chong's LazyVim configurations..."
git clone https://git.helenchong.dev/helenchong/LazyVim.git ~/.config/nvim
echo "Follow the rest of installation instructions to finish setting up Neovim:"
echo "https://git.helenchong.dev/helenchong/LazyVim"

echo "Updating Helen Chong's yadm repo origin URL..."
yadm remote set-url origin "git@git.helenchong.dev:helenchong/dotfiles.git"
echo "Updating Helen Chong's LazyVim configuration repo origin URL..."
cd "$HOME/.config/nvim" || return
git remote set-url origin "git@git.helenchong.dev:helenchong/LazyVim.git"
cd "$HOME"

echo "yadm bootstrap program executed."
echo "Reboot your system to apply changes."
