#!/usr/bin/env bash

echo "----------------------------"
echo "Install GE-Proton into Steam"
echo "----------------------------"

echo "Navigating to the Downloads directory..."
cd "$HOME/Downloads" || return

echo "Fetching the tarball URL of the latest version of GE-Proton version..."
TARBALL_URL=$(curl -s https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest | grep browser_download_url | cut -d\" -f4 | grep .tar.gz)

if [ -z "$TARBALL_URL" ]; then
	echo "No tarball URL found!"
	exit 1
fi

TARBALL_NAME=$(basename "$TARBALL_URL")
curl -L -o "$TARBALL_NAME" "$TARBALL_URL"

echo "Downloading tarball: $TARBALL_NAME..."
curl -# -L "$TARBALL_URL" -o "$TARBALL_NAME"

echo "Creating Steam's compatibility tools directory if it does not exist..."
mkdir -p ~/.steam/steam/compatibilitytools.d

echo "Extracting $TARBALL_NAME to Steam's compatibility tools directory..."
tar -xf "$TARBALL_NAME" -C ~/.steam/steam/compatibilitytools.d/

cd "$HOME" || return

echo "All done :)"
