#!/usr/bin/env bash

# Install required packages from the Arch Linux repository:
# sudo pacman -S --needed gum

# This script is used to write a scoped Git commit message.
# Scoped Commits: https://scopedcommits.com/
# It prompts the user to choose between Git and yadm,
# and the project/repository scope of the commit.
# And then prompts for thesummary and detailed description of the message

GIT_PROGRAM=$(gum choose "git" "yadm")
SCOPE=$(gum input --placeholder "scope")

# If the scope has a value, append a colon and a space
test -n "$SCOPE" && SCOPE="$SCOPE: "

# Pre-populate the input with "scope:" so that the user may change it
SUMMARY=$(gum input --value "$SCOPE" --placeholder "Summary of this change")
DESCRIPTION=$(gum write --placeholder "Details of this change")

# Commit these changes if user confirms
gum confirm "Commit changes?" && "$GIT_PROGRAM" commit -m "$SUMMARY" -m "$DESCRIPTION"
