#!/bin/sh

# Based on: https://github.com/charmbracelet/gum/blob/main/examples/commit.sh

# Install required packages from the Arch Linux repository:
# sudo pacman -S --needed gum

# This script is used to write a conventional Git commit message.
# It prompts the user to choose between Git and yadm,
# and the type of commit as specified in the conventional commit spec.
# And then prompts for the summary and detailed description of the message
# and uses the values provided. as the summary and details of the message.

GIT_PROGRAM=$(gum choose "git" "yadm")
TYPE=$(gum choose "fix" "feat" "docs" "style" "refactor" "test" "chore" "revert")
SCOPE=$(gum input --placeholder "scope")

# Since the scope is optional, wrap it in parentheses if it has a value.
test -n "$SCOPE" && SCOPE="($SCOPE)"

# Pre-populate the input with the type(scope): so that the user may change it
SUMMARY=$(gum input --value "$TYPE$SCOPE: " --placeholder "Summary of this change")
DESCRIPTION=$(gum write --placeholder "Details of this change")

# Commit these changes if user confirms
gum confirm "Commit changes?" && "$GIT_PROGRAM" commit -m "$SUMMARY" -m "$DESCRIPTION"
