#!/usr/bin/env bash

# Required program: unzip
# sudo pacman -S unzip

echo "----------------"
echo "Install poke-cli"
echo "----------------"

echo "Navigating to the Downloads directory..."
cd "$HOME/Downloads" || return

cd "$HOME" || return

echo "Fetching the ZIP archive download URL of the latest version of poke-cli..."
POKECLI_URL=$(curl https://api.github.com/repos/digitalghost-dev/poke-cli/releases/latest |
	grep "browser_download_url" |
	grep "poke-cli_Linux_x86_64.zip" |
	sed -E 's/.*"([^"]+)".*/\1/')

if [ -z "$POKECLI_URL" ]; then
	echo "No poke-cli ZIP archive download URL found!"
	exit 1
fi

ZIP_ARCHIVE=$(basename "$POKECLI_URL")

echo "Downloading ZIP file: $ZIP_ARCHIVE..."
curl -L -O "$POKECLI_URL"

OUTPUT_PATH="$HOME/.local/bin"
echo "Extracting poke-cli from the ZIP archive to $OUTPUT_PATH..."
unzip -j "$ZIP_ARCHIVE" poke-cli -d "$OUTPUT_PATH"

echo "All done :)"
